name: CI Pipeline for Karate Tests with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      - name: Build and Test with Gradle
        run: ./gradlew clean test